title: Leneme
email: your-email@example.com
author: Myself
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""
lang: 'en'

# Social Media
twitter_user: leneme
instagram_user: leneme
flickr_user: leneme
facebook_user: leneme

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

sass:
  sass_dir: assets/styles

exclude:
  - vendor
  - _assets
  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
